name: Java CI/CD Pipeline

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with maven
        run: mvn install -DskipTests=true
  deploy:
      name: Deploy
      runs-on: ubuntu-latest
      needs: build
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      environment:
        name: production
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
  
        - name: Deploy JAR
          run: |
            if [ "${GITHUB_ACTOR}" = "manhnv" ]; then
              sudo cp target/${{ env.projectname }}-${{ env.version }}.jar ${{ env.projectpath }}
              sudo chown -R ${{ env.projectuser }}. ${{ env.projectpath }}
              sudo kill -9 $(ps -ef | grep "${{ env.projectname }}-${{ env.version }}.jar" | grep -v grep | awk '{print $2}') || true
              sudo su ${{ env.projectuser }} -c "cd ${{ env.projectpath }}; nohup java -jar ${{ env.projectname }}-${{ env.version }}.jar > nohup.out 2>&1 &"
            else
              echo "Permission denied"
              exit 1
            fi
      env:
        projectname: myapp
        version: 1.0.0
        projectpath: /opt/myapp
        projectuser: appuser

  showlog:
    name: Show Log
    runs-on: ubuntu-latest
    needs: deploy
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Show Application Logs
        run: |
          sleep 20
          sudo su ${{ env.projectuser }} -c "cd ${{ env.projectpath }}; tail -n 10000 nohup.out"
    env:
      projectpath: /opt/myapp
      projectuser: appuser
